[BOAT] Enforce command
powercord-org/powercord-backend pull request #37
Opened 2020-10-17 15:07 UTC by BenSegal855

## A moderators dream come true
The enforce command allows a moderator to specify a target user and a rule they have broken. It then gets the rule in addition to how many times the target has broken it in the past. It then will automatically apply the proper action given the rule and the number of times it has been broken in the past. All info about who has broken which rules is stored in the `enforce` collection of the database.

2020-10-30 17:52 UTC, BenSegal855 commented
Upon looking back at the code I realized how absolutely ugly that switch statement is. I have a more elegant solution in mind and will be working on that soon:tm:. I am going to convert this PR to a draft while I work on making the code not look like it was written by a middle school student.

2020-10-30 19:04 UTC, BenSegal855 commented
okay the code is less ugly now. I have tested all possible actions. I did not test by waiting over ten days though so I am assuming the task handler works (it was tested thoroughly when added). All possible actions are automatically applied with the only exception being `mute/ban depending on severity` as the moderator needs to decide weather to mute or ban.

2020-11-02 11:35 UTC, Bowser65 requested changes

2020-11-02 11:35 UTC, Bowser65 commented on boat/commands/mod/enforce.js
> +}
That whole section is very similar to the one used in pc/rule command. It may be worth considering making a rule parser util, or parse all the rules at bot startup and cache them

2020-11-02 11:35 UTC, Bowser65 commented on boat/commands/mod/enforce.js
> +  }
I think reusing the regex used in mod commands here would allow for better flexibility, in case we ever update rules (updating the bot is effort and me dislike effort)

2020-11-02 11:35 UTC, Bowser65 commented on boat/commands/mod/enforce.js
> +  if (args[1] > 10 || args[1] < 1) {
This doesn't look super extensible; look up comment below about parsing rules since the info there is relevant for that too

2020-11-02 11:35 UTC, Bowser65 commented on boat/commands/mod/enforce.js
> +  }
Same comment as above, this doesn't look super extensible. Maybe a better approach would be keeping a record for each rule enforced (`{ _id: ObjectId(), userId: 'xxxxx', rule: 69, respMod: 'xxxx' }`) and then when looking up the records perform a count operation on them.

It also allows introducing the resp mod info, which could be used later on so we can lookup someone's past on the server, if necessary.
Moreover if we decide at some point to let punishments expire after some time, it's possible (since objectids carry the date in them). If someone gets muted because they did something a year ago, it's fair to say they deserve a 2nd mute rather than a mute.

2020-11-02 16:50 UTC, BenSegal855 commented on boat/commands/mod/enforce.js
> +}
Resolved by [8ed8c2f](https://github.com/powercord-org/powercord-backend/pull/37/commits/8ed8c2f99da0df9fca63e325a5c9366742325de8)

2020-11-02 17:41 UTC, BenSegal855 commented on boat/commands/mod/enforce.js
> +  }
Resolved by [f0c5866](https://github.com/powercord-org/powercord-backend/pull/37/commits/f0c5866f6623c4792ebc1b0dc5593d6b8a97bf90)

2020-11-02 18:54 UTC, BenSegal855 commented on boat/commands/mod/enforce.js
> +  if (args[1] > 10 || args[1] < 1) {
Resolved by [bde34f7](https://github.com/powercord-org/powercord-backend/pull/37/commits/bde34f7a147e5f8dfe3e9488c648bec0905cb1bb)

2020-11-02 18:54 UTC, BenSegal855 commented on boat/commands/mod/enforce.js
> +  }
Resolved by [bde34f7](https://github.com/powercord-org/powercord-backend/pull/37/commits/bde34f7a147e5f8dfe3e9488c648bec0905cb1bb)

2020-11-02 20:18 UTC, Bowser65 requested changes

2020-11-02 20:18 UTC, Bowser65 commented on boat/commands/mod/enforce.js
> +  const cases = await msg._client.mongo.collection('enforce').find({ userID: target, rule: ruleID }).toArray()
It may be preferable to use countDocuments here
Docs: http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#countDocuments

2020-11-02 20:28 UTC, BenSegal855 commented on boat/commands/mod/enforce.js
> +  const cases = await msg._client.mongo.collection('enforce').find({ userID: target, rule: ruleID }).toArray()
Resolved by [031cdd2](https://github.com/powercord-org/powercord-backend/pull/37/commits/031cdd26df6db7c49608a9ad60c88a4743b47123)

2020-11-02 20:30 UTC, Bowser65 approved these changes

2020-11-02 20:30 UTC, merged