[BOAT] Member Log
powercord-org/powercord-backend pull request #47
Opened 2020-12-05 09:08 UTC by BenSegal855

This PR adds a member log because I find them useful. I had the unfortunate idea to write all this code after midnight so it may not be great and I'm always willing to fix stuff to make it better so just let me know. 

### What gets logged
member joins
member leaves
nick updates
role adds
role removes

### What do they look like
They look like this
![gotta love embeds](https://cdn.discordapp.com/attachments/723241105323327581/784706806303686696/unknown.png)

### Why do you want this again?
So I can go back to a normal life and have #welcome muted, is that too much to ask.

### Why all these questions?
idk its early o'clock in the morning and I am probably just overtired at this point

### Will this unnecessarily long PR description ever end?
Yeah it can end here I guess.

2020-12-07 17:10 UTC, BenSegal855 commented on boat/memberlog.js
> +    else if (oldMember.roles !== newMember.roles) embed = this.roleChange(newMember, oldMember)
So I just realized that js sucks at list comparison and late o'clock Ben didnt realize that there is a huge flaw in the role update logs because of it. I am fixing now and should be resolved soon:tm:

2020-12-07 18:35 UTC, BenSegal855 commented on boat/memberlog.js
> +    else if (oldMember.roles !== newMember.roles) embed = this.roleChange(newMember, oldMember)
Resolved by [c8353bb](https://github.com/powercord-org/powercord-backend/pull/47/commits/c8353bb22236c51c62cb0f72b8fb52ff0c845adb)

2020-12-13 12:54 UTC, cyyynthia requested changes

2020-12-13 12:54 UTC, cyyynthia commented on boat/memberlog.js
> +    bot.on('guildMemberAdd', (guild, member) => this.memberAdd(bot, guild, member))
Prefer doing something similar to the modlog, and keep bot as a class property and simply bind your callbacks
(ref: https://github.com/powercord-org/powercord-backend/blob/my-awesome-branch/boat/modlog.js#L41)

2020-12-13 12:54 UTC, cyyynthia commented on boat/memberlog.js
> +    if (newRoleNames[0]) {
```suggestion
    if (newRoleNames.length > 0) {
```

2020-12-13 12:54 UTC, cyyynthia commented on boat/memberlog.js
> +    if (oldRoleNames[0]) {
```suggestion
    if (oldRoleNames.length > 0) {
```

2020-12-13 12:54 UTC, cyyynthia commented on boat/memberlog.js
> +    const oldRoleIDs = oldMember.roles.filter(this._comparer(newMember.roles))
```suggestion
    const newRoleIDs = newMember.roles.filter(r => !oldMember.roles.includes(r))
    const oldRoleIDs = oldMember.roles.filter(r => !newMember.roles.includes(r))
```
Might also be worth renaming the variables to "addedRoleIds" and "removedRoleIds", since it's imo a better naming choice.

It's also not enforced by the linter but I prefer strictCamelCase, which means `somethingId` shouldn't be named `somethingID`. The camelCase rule goes over the rule of having abbreviations in uppercase.

2020-12-13 12:54 UTC, cyyynthia commented on boat/memberlog.js
> +  }
See above, but this is just a reimpl of a "does not include" which is doable by simply inverting JS' include function.

2020-12-13 16:14 UTC, BenSegal855 commented on boat/memberlog.js
> +  }
Resolved by [397cabb](https://github.com/powercord-org/powercord-backend/pull/47/commits/397cabbc1e1268c58b28f90093f18678a78eb6f8)

2020-12-13 16:15 UTC, BenSegal855 commented on boat/memberlog.js
> +    bot.on('guildMemberAdd', (guild, member) => this.memberAdd(bot, guild, member))
Resolved by [6295f22](https://github.com/powercord-org/powercord-backend/pull/47/commits/6295f228e96d188cd8a91f23f8e7c8803f08f715)

2020-12-15 13:56 UTC, cyyynthia approved these changes

2020-12-15 13:57 UTC, merged