[BOAT] Auto ban muted users who have many infractions if they attempt to circumvent the mute
powercord-org/powercord-backend pull request #56
Opened 2021-01-02 04:59 UTC by BenSegal855

The title is long but descriptive. This PR will automatically ban a user if they leave while muted and have more than four rule infractions. It also adds a rule infraction every time they leave while muted under rule `-1`. That way if a user is a repeat rule breaker, they will be auto banned sooner than if they have never broken a rule. Four was arbitrarily choses as the number but it can easily be changed by changing the `maxInfractions` const at the top of boat/src/modules/mutedban.ts

2021-01-02 10:39 UTC, cyyynthia requested changes

2021-01-02 10:39 UTC, cyyynthia commented on package.json
> +    "bot:build": "rm -rf dist && tsc --build boat/tsconfig.json",
Although it may be useful to drop the dist folder since the bot now uses an autoloader and stale files might still be there, removing the *whole* dist folder in a script-specific action is not ideal, and will still yield failures in watch mode anyway. I'd say this isn't a necessary step, and should be handled by the end user (or at least remove only the target's dist folder). I know the build script does it too, but I'm unsure if I'll keep it on the long term since the use of `rm` makes it difficult to jump in on Windows if you don't have the proper toolchain installed.

2021-01-02 10:39 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +  if (!('roles' in member)) return
Merge conditions

2021-01-02 10:39 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +const maxInfractions = 4
UPPER_CASE

2021-01-02 10:39 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +    ban(guild, member.id, this.user, '[AUTOMATIC] Left while muted one too many times.')
YOU DON'T NEED TO YELL THE FACT ITS AUTOMATIC (and tbh I don't even know if it's actually necessary)

2021-01-02 10:39 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +  const bans = (await guild.getBans()).map(ban => ban.user.id)
Use a promise composition instead, looks less messy than a wrapped await
```suggestion
  const bans = await guild.getBans().then((bans) => bans.map((ban) => ban.user.id))
```

2021-01-02 22:12 UTC, BenSegal855 commented on package.json
> +    "bot:build": "rm -rf dist && tsc --build boat/tsconfig.json",
Resolved by [0d2efd7](https://github.com/powercord-org/powercord-backend/pull/56/commits/0d2efd7f9663fc1b3ed267ea34ec066319b6c7a3)

2021-01-02 22:12 UTC, BenSegal855 commented on boat/src/modules/mutedban.ts
> +  if (!('roles' in member)) return
Resolved by [be7910e](https://github.com/powercord-org/powercord-backend/pull/56/commits/be7910ed30e1db99b6132efab0b249aef42a574e)

2021-01-02 22:12 UTC, BenSegal855 commented on boat/src/modules/mutedban.ts
> +const maxInfractions = 4
Resolved by [be7910e](https://github.com/powercord-org/powercord-backend/pull/56/commits/be7910ed30e1db99b6132efab0b249aef42a574e)

2021-01-02 22:12 UTC, BenSegal855 commented on boat/src/modules/mutedban.ts
> +    ban(guild, member.id, this.user, '[AUTOMATIC] Left while muted one too many times.')
Resolved by [be7910e](https://github.com/powercord-org/powercord-backend/pull/56/commits/be7910ed30e1db99b6132efab0b249aef42a574e)

2021-01-03 10:54 UTC, cyyynthia requested changes

2021-01-03 10:54 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +import { ban } from '../mod.js';
```suggestion
import { ban } from '../mod.js'
```

2021-01-03 10:54 UTC, cyyynthia commented on boat/src/modules/mutedban.ts
> +import config from '../config.js'
I'd prefer having the config imported last

2021-01-03 16:47 UTC, BenSegal855 commented on boat/src/modules/mutedban.ts
> +import { ban } from '../mod.js';
Resolved by [04abf72](https://github.com/powercord-org/powercord-backend/pull/56/commits/04abf7227bd4211645f297777717d7d6a2b203c6)

2021-01-03 16:47 UTC, BenSegal855 commented on boat/src/modules/mutedban.ts
> +import config from '../config.js'
Resolved by [04abf72](https://github.com/powercord-org/powercord-backend/pull/56/commits/04abf7227bd4211645f297777717d7d6a2b203c6)

2021-01-03 16:48 UTC, cyyynthia approved these changes

2021-01-03 16:48 UTC, merged