[BOAT] auto raid moderation
powercord-org/powercord-backend pull request #69
Opened 2021-03-31 16:54 UTC by BenSegal855

This PR will kick any user who joined the guild less than one minute prior and sent the same message three times. It will ban any user who does this twice.

2021-04-11 17:20 UTC, cyyynthia requested changes
There's in addition to the comments I left also a fair chunk of code style issues (no semi, no `undefined` (use `void 0` instead), ...).

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +class RaidMessage {
Couldn't this be simplified to a plain object created in `addRaidMessage`?

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +const messageBuffer = new Collection(RaidMessage)
Why use a collection from Eris here? This could easily be replaced by a vanilla Map/Set, or I'm missing something?

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  if (msg.guildID !== config.discord.ids.serverId || !msg.member || msg.member.joinedAt < Date.now() - 60e3) return;
A minute is rather short, and since the source is public people will just wait before spamming (because we know from which very wholesome community some raids were coming from) <!-- vizality cough cough -->

Maybe increase the limit to at least 10mins (to match Discord's moderation setting), or even higher like a day. It might be a good idea to always catch accounts older than a month to make use of burner accounts more annoying.

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  if (isRaider(msg.author.id, msg.content)) {
It may be a good idea when we detect an incoming wave of raiders to automatically set the server moderation level to highest for a set period of time to help slow down the wave.

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +      ban(msg.channel.guild, msg.author.id, this.user, 'Repeat raider')
You can tell Discord to delete messages along with the ban, to avoid having to do it yourself.

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +      kick(msg.channel.guild, msg.author.id, this.user, 'Detected raid spam')
Same as above, except that here you'd do a softban (ban & unban right after). Must come with proper flag in the reason field so the mod logger can mark the ban as a kick and ignore the unban event (a `[Softban]` flag should do the trick I think?)

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  }
```suggestion
  let count = raiderBuffer.get(raiderHash) ?? 0
```

2021-04-11 17:20 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  const raiderHash = createHash('sha256').update(`${user}${message}`).digest('base64').toString()
Why use a hash here? I'm assuming it's to save on memory (and to store just 32 bytes instead of up to 2037 chars), but then you could just use sha1 and compare buffers instead, I think?

2021-04-12 00:07 UTC, cyyynthia requested changes

2021-04-12 00:07 UTC, cyyynthia commented on boat/src/commands/mod/softban.ts
> +const USAGE_STR = `Usage: ${config.discord.prefix}ban <mention || id> [reason]`
```suggestion
const USAGE_STR = `Usage: ${config.discord.prefix}softban <mention || id> [reason]`
```

2021-04-12 00:07 UTC, cyyynthia commented on boat/src/commands/mod/softban.ts
> +import type { GuildTextableChannel, Message } from 'eris'
Missing license header

2021-04-12 00:07 UTC, cyyynthia commented on boat/src/modules/modlog.ts
> +      reason = reason.replace('[soft]', '')
```suggestion
      reason = reason.replace('[soft] ', '')
```

2021-04-12 00:15 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  if (isRaider(msg.author.id, msg.content)) {
Implementing this should be fairly easy, as it's basically a timer: if in the last let's say 5mins we catch 5 people, call [Guild#edit](https://abal.moe/Eris/docs/Guild#function-edit) and schedule a cleanup task which sets it back to what it was later

2021-04-12 03:41 UTC, BenSegal855 commented on boat/src/modules/raidmod.ts
> +  if (isRaider(msg.author.id, msg.content)) {
Resolved by [397e119](https://github.com/powercord-org/powercord-backend/pull/69/commits/397e119eaea79a926857df1446d42790e04cdd54)

2021-04-12 11:35 UTC, cyyynthia requested changes
A lot of nitpicking here (and I didn't note inconsistencies in where periods are placed :p)

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/endraid.ts
> +export async function executor (msg: Message<GuildTextableChannel>,): Promise<Message | void> {
```suggestion
export function executor (msg: Message<GuildTextableChannel>): void {
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/endraid.ts
> +    return msg.channel.createMessage('no')
```suggestion
    msg.channel.createMessage('no')
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/endraid.ts
> +    return msg.channel.createMessage('Raid mode is not currently active.')
```suggestion
    msg.channel.createMessage('Raid mode is not currently active.')
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/endraid.ts
> +  return msg.channel.createMessage('Raid mode disabled.')
```suggestion
  exitRaidMode(msg.channel.guild, msg.author)
  msg.channel.createMessage('Raid mode disabled.')
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +export async function executor (msg: Message<GuildTextableChannel>, [ rawDuration ]: [string]): Promise<Message | void> {
```suggestion
export function executor (msg: Message<GuildTextableChannel>, [ rawDuration ]: [ string ]): void {
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +    return msg.channel.createMessage('no')
```suggestion
    msg.channel.createMessage('no')
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +    return msg.channel.createMessage('Raid mode is currently active.')
```suggestion
    msg.channel.createMessage('Raid mode is currently active.')
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +    return msg.channel.createMessage(USAGE_STR)
```suggestion
    msg.channel.createMessage(USAGE_STR)
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +    return msg.channel.createMessage('Invalid duration')
```suggestion
    msg.channel.createMessage('Invalid duration')
    return
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +  return msg.channel.createMessage('Raid mode activated.')
```suggestion
  enterRaidMode(msg.channel.guild, msg.author, duration)
  msg.channel.createMessage('Raid mode activated.')
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/raid.ts
> +import config from '../../config.js'
Import config last (not a linting rule or anything, just a preference)

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/index.ts
>  import config from './config.js'
Prefer importing config last

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +import config from '../config.js'
Prefer importing config last

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +let activeRaiders = 0;
```suggestion
let activeRaiders = 0
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/raidMode.ts
> +import config from './config.js'
Prefer importing config last

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/modules/raidmod.ts
> +  }
```suggestion
  const count = raiderBuffer.get(hash)
  if (!count) return

  if (count === 1) {
    raiderBuffer.delete(hash)
  } else {
    raiderBuffer.set(hash, count - 1)
  }
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/raidMode.ts
> + * @param mod - the moderator responsible fro lowering the verification level
```suggestion
 * @param mod - the moderator responsible for lowering the verification level
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/commands/mod/softban.ts
> +  msg.channel.createMessage('yeeted')
```suggestion
  msg.channel.createMessage('yeeted & censored')
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/modules/modtasks.ts
> + * @param userId - the user the task will be operation on
```suggestion
 * @param userId - the user the task will be operated on
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/raidMode.ts
> + * @param mod - the moderator responsible for rasing the verification level
```suggestion
 * @param mod - the moderator responsible for raising the verification level
```

2021-04-12 11:35 UTC, cyyynthia commented on boat/src/util.ts
> + * @returns the numerical representation of `duration`
```suggestion
 * @returns the numerical representation of `duration` in ms
```

2021-04-17 10:53 UTC, cyyynthia approved these changes

2021-04-17 10:53 UTC, merged