[BOAT] Use new timestamp mentions when possible
powercord-org/powercord-backend pull request #76
Opened 2021-06-18 04:29 UTC by BenSegal855

This PR makes use of timestamp mentions in the deleted log, member log, and lookup commands. 

*This is will be marked as a draft until this feature fully rolls out

2021-07-13 01:54 UTC, BenSegal855 commented
Timestamp markdown has been released on all platforms. This PR is ready to review.

2021-07-15 21:08 UTC, cyyynthia requested changes

2021-07-15 21:08 UTC, cyyynthia commented on packages/boat/src/modules/mod/memberlog.ts
> +      description: `<@${member.id}> created their accout at <t${Math.floor(member.createdAt / 1000)}> (${elapsed})`,
the timestamp here is malformed (missing `:`); here `R`  formatting may be best and ditch the need for elapsed

might also remove the need for `prettyPrintTimeSpan` altogether

2021-07-15 21:08 UTC, cyyynthia commented on packages/boat/src/commands/mod/lookup.ts
> +      description: `**Account created:** <t:${createdAt}> (${prettyPrintTimeSpan(Date.now() - member.createdAt)} ago)\n\n**Joined:** <t:${joinedAt}> (${prettyPrintTimeSpan(Date.now() - member.joinedA
See comment for modlog.ts

2021-07-15 21:08 UTC, cyyynthia commented on packages/boat/src/commands/mod/lookup.ts
> +        occurrences: [ `• <t:${timestamp}> (<t:${timestamp}:R>)` ],
no need to have both; hovering works

2021-07-15 21:08 UTC, cyyynthia commented on packages/boat/src/commands/mod/lookup.ts
> +      infractions[infractions.indexOf(infraction)].occurrences.push(`• <t:${timestamp}> (<t:${timestamp}:R>)`)
no need to have both; hovering works

2021-07-15 21:11 UTC, BenSegal855 commented on packages/boat/src/commands/mod/lookup.ts
> +      description: `**Account created:** <t:${createdAt}> (${prettyPrintTimeSpan(Date.now() - member.createdAt)} ago)\n\n**Joined:** <t:${joinedAt}> (${prettyPrintTimeSpan(Date.now() - member.joinedA
No changes were made for modlog.ts. Did you mean memberlog.ts?

2021-07-15 21:12 UTC, cyyynthia commented on packages/boat/src/commands/mod/lookup.ts
> +      description: `**Account created:** <t:${createdAt}> (${prettyPrintTimeSpan(Date.now() - member.createdAt)} ago)\n\n**Joined:** <t:${joinedAt}> (${prettyPrintTimeSpan(Date.now() - member.joinedA
yes

2021-07-15 21:15 UTC, BenSegal855 commented on packages/boat/src/modules/mod/memberlog.ts
> +      description: `<@${member.id}> created their accout at <t${Math.floor(member.createdAt / 1000)}> (${elapsed})`,
I kept the elapsed time and `prettyPrintTimeSpan` in for two reasons. First, its more precise than how it gets parsed using markdown (and I like precision). Second, it shows the time relative to when they actually joined the server instead of relative to whenever someone happens to be viewing the log. In my eyes this is more useful as it makes it much easier to spot new accounts when looking at the logs after the users has joined.

2021-07-15 21:16 UTC, cyyynthia commented on packages/boat/src/modules/mod/memberlog.ts
> +      description: `<@${member.id}> created their accout at <t${Math.floor(member.createdAt / 1000)}> (${elapsed})`,
Fair point

2021-07-19 09:36 UTC, cyyynthia requested changes

2021-07-19 09:36 UTC, cyyynthia commented on packages/boat/src/modules/mod/memberlog.ts
> +      description: `<@${member.id}> created their accout at <t${Math.floor(member.createdAt / 1000)}> (${elapsed})`,
The timestamp markup is still malformed (missing `:`). You may also want to add the "ago" thing like you did in lookup.ts

2021-07-20 17:34 UTC, cyyynthia commented
Either you forgot to push, or you really want me to repeat a 3rd time my last review comment lmao

2021-07-20 19:51 UTC, cyyynthia approved these changes

2021-07-20 19:52 UTC, merged