[BOAT] Fix logger so bulk deletes and large message deletes still get logged
powercord-org/powercord-backend pull request #78
Opened 2021-07-14 21:48 UTC by BenSegal855

This PR fixes two bugs in the logger module.
1. The condition that checked if a bulk delete should be logged compared the first messages channel id to the guild id from the config <:pawa_knock_head:842001776819306526>. 
1. Messages longer than 1700 characters are now uploaded to hastebin.powercord.dev to ensure the message sent in the logs is under 2000 characters.

2021-07-15 21:03 UTC, cyyynthia requested changes
Not a big fan of the current way the message is composed; double check my suggestions as the formatting may be a bit messed up

2021-07-15 21:03 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +
```suggestion
  let msg
  if (message.content.length > 1700) {
    const res = await fetch('https://haste.powercord.dev/documents', {
      method: 'POST',
      body: stringifyDiscordMessage(message),
    }).then((r) => r.json())
    msg = `*Message too long* <https://haste.powercord.dev/${res.key}.txt>`
  } else {
    msg = stringifyDiscordMessage(message).replace(/`/g, `\`${ZWS}`) || '*No contents*'
  }

```

2021-07-15 21:03 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +      || '*No contents*')}${hasteBin}\n${attachments}`
```suggestion
    .replace(/\$message/g, `${msg}\n${attachments}`)}`
```

2021-07-15 21:23 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +
> *Ben in powercord-core:*
> I believe that will put the link in the codeblock and make it unclickable. I can try to work out a cleaner way to do it with the link sill being outside the codeblock but I think it would still need a flag.

That's actually true; to make it cleaner `attachments` could be renamed `extra` and declared with a let, and then append the hastebin url if necessary

2021-07-15 21:24 UTC, BenSegal855 commented on packages/boat/src/modules/mod/logger.ts
> +
I'll make that change.

2021-07-19 09:30 UTC, cyyynthia requested changes

2021-07-19 09:30 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +    .replace(/\$message/g, !bulk && cleanContent.length > 1700
The length measurement can be fooled as we append additional characters in addition to the <= 1700 characters we check (zws after `), which could be problematic

2021-07-19 09:30 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +  ))).join('\n\n')
```suggestion
  const list = []
  for (const msg of msgs) {
    list.push('author' in msg
      ? format(LIST_TEMPLATE, msg, true)
      : `A message in #${msg.channel.name} that was not cached`)
  }
```
+ necessary changes in other places now that list is an array

2021-07-19 21:38 UTC, BenSegal855 commented on packages/boat/src/modules/mod/logger.ts
> +  ))).join('\n\n')
Any reason not to use Array.map like the below snippet and then handle the processes elsewhere?
```js
const list = msgs.map((msg) =>
    'author' in msg
      ? format(LIST_TEMPLATE, msg, true)
      : `A message in #${msg.channel.name} that was not cached`)
// Code that handles promises.
```

2021-07-19 21:52 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +  ))).join('\n\n')
A bit less clean; I actually forgot the await in front of format in my suggestion, that's updated

2021-07-20 17:36 UTC, cyyynthia requested changes

2021-07-20 17:36 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +    const channelName = this.guilds.get(config.discord.ids.serverId)?.channels.get(msg.channel.id)?.name || msg.channel.id
Bulk deletes can only include messages from a single channel. Fetching for every message the channel is not a good idea.

2021-08-03 16:02 UTC, cyyynthia requested changes

2021-08-03 16:02 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +    .replace(/\$message/g, !bulk && cleanContent.length > 1700
This problem hasn't been addressed

2021-08-08 15:31 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +      body: cleanContent,
only the output of `stringifyDiscordMessage` is needed for here, replacing the markdown codeblocks is unnecessary

2021-08-23 15:24 UTC, BenSegal855 commented on packages/boat/src/modules/mod/logger.ts
> +      body: cleanContent,
While escaping backticks isn't necessary here, not adding the zws's would require another call to `stringifyDiscordMessage()` while keeping them escaped requires no additional complexity and has no visible effect in the result.

2021-11-22 17:03 UTC, cyyynthia commented on packages/boat/src/modules/mod/logger.ts
> +      body: cleanContent,
Addressed in fa39bc0

2021-11-22 17:07 UTC, cyyynthia approved these changes
Made the appropriated changes to unblock the PR

2021-11-22 17:07 UTC, merged